# Generated by Django 4.2.20 on 2025-04-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_to_buy', models.TextField(blank=True, null=True)),
                ('how_to_buy', models.TextField(blank=True, null=True)),
                ('how_to_redeem', models.TextField(blank=True, null=True)),
                ('bulk_detail', models.TextField(blank=True, null=True)),
                ('process_duration_detail', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('merchant_coverage_detail', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('validity', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_details',
            },
        ),
    ]
