# Generated by Django 4.2.20 on 2025-04-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reward_brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brands', models.ManyToManyField(related_name='reward_category_brands', to='reward_brands.rewardbrand')),
            ],
            options={
                'db_table': 'reward_categories',
            },
        ),
    ]
