# Generated by Django 4.2.20 on 2025-04-23 01:44

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('reward_brands', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('country', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed'), ('multi-value', 'Multi Value'), ('range', 'Range'), ('custom', 'Custom')], default='fixed', max_length=20)),
                ('price', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='contacts.contact')),
                ('purchase_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='purchases.purchasedetail')),
                ('reward_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_set', to='reward_brands.rewardbrand')),
            ],
        ),
    ]
