# Generated by Django 4.2.20 on 2025-04-29 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('where_to_buy', models.TextField(blank=True, null=True)),
                ('how_to_buy', models.TextField(blank=True, null=True)),
                ('how_to_redeem', models.TextField(blank=True, null=True)),
                ('bulk_detail', models.TextField(blank=True, null=True)),
                ('process_duration_detail', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('merchant_coverage_detail', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('validity', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_details',
            },
        ),
        migrations.CreateModel(
            name='RewardBrand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('purchase_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_brands', to='rewards.purchasedetail')),
            ],
            options={
                'db_table': 'reward_brands',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('category_slug', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed'), ('multi-value', 'Multi Value'), ('range', 'Range'), ('custom', 'Custom')], default='fixed', max_length=20)),
                ('price', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reward_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='rewards.rewardbrand')),
            ],
            options={
                'db_table': 'rewards',
            },
        ),
    ]
