# Generated by Django 4.2.20 on 2025-04-23 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        ('contacts', '0001_initial'),
        ('rewards', '0001_initial'),
        ('reward_brands', '0001_initial'),
        ('rewards_categories', '0001_initial'),
        ('rewards_types', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardbrand',
            name='categories',
            field=models.ManyToManyField(related_name='reward_brands_categories', to='rewards_categories.rewardcategory'),
        ),
        migrations.AddField(
            model_name='rewardbrand',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_brands', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='rewardbrand',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_brands', to='platforms.platform'),
        ),
        migrations.AddField(
            model_name='rewardbrand',
            name='purchase_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_brands', to='purchases.purchasedetail'),
        ),
        migrations.AddField(
            model_name='rewardbrand',
            name='rewards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_brands', to='rewards.reward'),
        ),
        migrations.AddField(
            model_name='rewardbrand',
            name='types',
            field=models.ManyToManyField(related_name='reward_brands_types', to='rewards_types.rewardtype'),
        ),
    ]
